### ISSUE TITLE
Traceback when calling get-job-templates in MS teams.

### ISSUE THREAD

**Issue by jeffkala** [nautobot/nautobot-plugin-chatops-ansible#38]
### Environment
* Python version:  3.7
* Nautobot version:  1.2.5
* nautobot-plugin-chatops-ansible version:  1.0.3
* Running via MS teams.

### Steps to Reproduce
1. run `ansible get-job-templates`

### Expected Behavior
Return the jobs.

### Observed Behavior
```
[2022-04-20 15:05:25,068: ERROR/ForkPoolWorker-1] Task nautobot_chatops.utils.celery_worker_task[e3e7da05-e20b-4835-aaf1-ca9f7977ec29] raised unexpected: KeyError('inventory')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/nautobot_chatops/utils.py", line 44, in celery_worker_task
    context=context,
  File "/usr/local/lib/python3.7/site-packages/nautobot_chatops_ansible/worker.py", line 44, in ansible
    return handle_subcommands("ansible", subcommand, **kwargs)
  File "<decorator-gen-2>", line 2, in handle_subcommands
  File "/usr/local/lib/python3.7/site-packages/prometheus_client/context_managers.py", line 81, in wrapped
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/nautobot_chatops/workers/__init__.py", line 298, in handle_subcommands
    result = registry[command]["subcommands"][subcommand]["worker"](dispatcher, *params)
  File "/usr/local/lib/python3.7/site-packages/nautobot_chatops/workers/__init__.py", line 187, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/nautobot_chatops_ansible/worker.py", line 196, in get_job_templates
    for entry in job_templates
  File "/usr/local/lib/python3.7/site-packages/nautobot_chatops_ansible/worker.py", line 196, in <listcomp>
    for entry in job_templates
KeyError: 'inventory'
```

**Comment by jeffkala** [comment]
Note that a job-template that is set to `prompt for inventory` does not actually include an `inventory` key in the results json payload from the api.
