### ISSUE TITLE
get_job_templates fails with `inventory` error.

### ISSUE THREAD

**Issue by jeffkala** [nautobot/nautobot-plugin-chatops-ansible#42]
### Environment
* Python version: 3.7
* Nautobot version:  1.3.8
* nautobot-plugin-chatops: 1.8.0
* nautobot-plugin-chatops-ansible version:  1.0.3

When running `get_job_templates` via chatops in a MS team chat client it results in a failure about `inventory`.

### Steps to Reproduce
1. Execute `ansible get_job_templates`

### Expected Behavior
Return a list of job templates from AWX/Tower.

### Observed Behavior
Exception in the chat response about `inventory`.
`An internal error occured 'Inventory'`

### Full traceback
```
[2022-07-27 14:33:24,850: ERROR/ForkPoolWorker-2] Task nautobot_chatops.utils.celery_worker_task[80b5175a-81fb-44ca-b8ef-cbaffe6a8d70] raised unexpected: KeyError('inventory')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/nautobot_chatops/utils.py", line 44, in celery_worker_task
    context=context,
  File "/usr/local/lib/python3.7/site-packages/nautobot_chatops_ansible/worker.py", line 44, in ansible
    return handle_subcommands("ansible", subcommand, **kwargs)
  File "<decorator-gen-2>", line 2, in handle_subcommands
  File "/usr/local/lib/python3.7/site-packages/prometheus_client/context_managers.py", line 81, in wrapped
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/nautobot_chatops/workers/__init__.py", line 298, in handle_subcommands
    result = registry[command]["subcommands"][subcommand]["worker"](dispatcher, *params)
  File "/usr/local/lib/python3.7/site-packages/nautobot_chatops/workers/__init__.py", line 187, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/nautobot_chatops_ansible/worker.py", line 196, in get_job_templates
    for entry in job_templates
  File "/usr/local/lib/python3.7/site-packages/nautobot_chatops_ansible/worker.py", line 196, in <listcomp>
    for entry in job_templates
KeyError: 'inventory'
```
Releated to this call: https://github.com/nautobot/nautobot-plugin-chatops-ansible/blob/8c91d0d693b1099ae0f1ab0d1ea899eccecd5081/nautobot_chatops_ansible/worker.py#L193

Oddly looking at the api result this code block with the `.get()` can should work based on what I'm seeing.  However, it maybe a better option to be more explict with the call for `ask for inventory on launch` and look at its bool value. It is available at `entry["ask_inventory_on_launch"]`

**Comment by jeffkala** [comment]
Was already fixed by https://github.com/nautobot/nautobot-plugin-chatops-ansible/pull/39/files, realized there just hasn't been a new release since these fixes were implemented.
